### ISSUE TITLE
Add User Story Template for Issues

### ISSUE THREAD

**Issue by dimitriosxmi** [Nikoskak2000/The-hero-is-useless#15]
We are going to start using a specific format for writting user stories when it comes to new features for the project.
This is going to make the process of writing Issues easier by guiding the user.

<details>
<summary>Click here for steps tl;dr summary</summary>
1. Go to repository settings <br>
2. Scroll down and click click `Set up templates` button in the issues category <br>
3. Click `Add template` button and select `Feature request` and then click `Preview and edit` button, click the pen icon to enter edit mode<br>
4. Fill the form, `Template name` = "User Story Template", `About` = "A template to create user stories. Remove all ... and examples before posting.", `Labels` = "enhancement", `Template content` = <br>

```
[Link to documentation]()
(If all infos are provided in the linked documentation(s), remove all bellow the linked documentation(s))
<hr>

## Value Proposition

**As a** ... (Player Character, Player in the paused game menu, Player using the truck vehicle...)  
**I want to** ... (describe the goal)  
**so that/in order to** ... (describe the reason)  
​

## Description

... (Wireframe, scribble, design, text, or a combination of those)
​

## Acceptance Criteria

- [ ] Describe every scenario in detail
- [ ] e.g. the gate should open after the player pushes down the lever
- [ ] e.g. the player must be able to pass through the gate without special movement
- [ ] ...
      ​

## Tasks

- [ ] list the coding tasks that need to be performed
- [ ] e.g. create branch `feature/xyz`
- [ ] e.g. create gate assets [Link to documentation](<hacknplan link>) and import into project
- [ ] e.g. create scene for gate with script
- [ ] e.g. create scene for level with script
- [ ] e.g. hook scenes together in a test world scene with a player and test the functionality
- [ ] ...
```
5. Done? than click `Propose changes` button at top right, and click `Commit changes` button from right sidebar.
Finished!
</details>

## Step 1
| Description |
| :---: |
| Go to `Settings` tab of the repository <details><summary><h4>Click here for hint</h4></summary>![Screenshot_9](https://github.com/Nikoskak2000/The-hero-is-useless/assets/31593501/8bdd5491-eba2-44ce-831b-6d6ac8e293b6) </details> |

## Step 2
| Description |
| :---: |
| In the `General` tab, scroll down to the `Features` section and under the `Issues` category click the button **`Set up templates`** <details><summary><h4>Click here for hint</h4></summary>![Screenshot_3](https://github.com/Nikoskak2000/The-hero-is-useless/assets/31593501/48934943-22f2-4f2f-9839-ee74c7538098)</details>

## Step 3
| Description |
| :---: |
| You are now navigated in the issues templates page where you can edit the templates, here click the `Add template: select` button and underneath it a drop-down will pop, from the selection click the option `Feature request`, this will create a new feature request template card, in that card now click the `Preview and edit` button and from the drop-down card click the pen icon <details><summary><h4>Click here for hint</h4></summary> ![Screenshot_4](https://github.com/Nikoskak2000/The-hero-is-useless/assets/31593501/7180cceb-6f9f-4668-aff3-aa688df7247c) ![Screenshot_5](https://github.com/Nikoskak2000/The-hero-is-useless/assets/31593501/09921391-0244-48a7-84b9-53ad7f40bee3) ![Screenshot_6](https://github.com/Nikoskak2000/The-hero-is-useless/assets/31593501/20f250b9-03fc-4924-ab98-de549288e5ff) |

## Step 4
| Description |
| :---: |
| A form will now be open with multiple input fields. You can leave `Template name` input field by default as Feature Request as it is or rename it to "User Story Template" this is up to your preference. In the `About` input field type this "A template to create user stories. Remove all ... and examples before posting.". In the `Template content` copy paste this text bellow |
```
[Link to documentation]()
(If all infos are provided in the linked documentation(s), remove all bellow the linked documentation(s))
<hr>

## Value Proposition

**As a** ... (Player Character, Player in the paused game menu, Player using the truck vehicle...)  
**I want to** ... (describe the goal)  
**so that/in order to** ... (describe the reason)  
​

## Description

... (Wireframe, scribble, design, text, or a combination of those)
​

## Acceptance Criteria

- [ ] Describe every scenario in detail
- [ ] e.g. the gate should open after the player pushes down the lever
- [ ] e.g. the player must be able to pass through the gate without special movement
- [ ] ...
      ​

## Tasks

- [ ] list the coding tasks that need to be performed
- [ ] e.g. create branch `feature/xyz`
- [ ] e.g. create gate assets [Link to documentation](<hacknplan link>) and import into project
- [ ] e.g. create scene for gate with script
- [ ] e.g. create scene for level with script
- [ ] e.g. hook scenes together in a test world scene with a player and test the functionality
- [ ] ...
```
| Description |
| :---: |
| Additionally you may set the `Labels` to "enhancement" but that's optional. The result should look something like the hint bellow <details><summary><h4>Click here for hint</h4></summary>![Screenshot_11](https://github.com/Nikoskak2000/The-hero-is-useless/assets/31593501/5b15270e-283a-444f-a39b-b52baaaea37d) ![Screenshot_12](https://github.com/Nikoskak2000/The-hero-is-useless/assets/31593501/2c8f85c8-6892-4e9c-9d96-176433b538ca)</details> |

## Step 5
| Description |
| :---: |
| Once the form is completed, click the `Propose changes` button on the top right of the page and side bar will appear, from there click the `Commit changes` button and you're good to go! <details><summary><h4>Click here for hint</h4></summary>![Screenshot_13](https://github.com/Nikoskak2000/The-hero-is-useless/assets/31593501/6f94b2d2-a012-4951-a254-7a5d8625a2d8) ![Screenshot_14](https://github.com/Nikoskak2000/The-hero-is-useless/assets/31593501/b363aadd-dbd6-4868-985a-310eeb45f098)</details> |

| If all was done correctly, you should be able to see a new `Get started` button when attempting to create a new `Issue` <details><summary><h4>Click here for hint</h4></summary>![Screenshot_15](https://github.com/Nikoskak2000/The-hero-is-useless/assets/31593501/98e07f3b-b927-49c2-af61-d6f6026eb293) ![Screenshot_16](https://github.com/Nikoskak2000/The-hero-is-useless/assets/31593501/dd4bfb33-8a07-42a1-a63c-d595fbd3d740)</details> |
| :---: |
