### ISSUE TITLE
Setup HackNPlan Design Model's structure

### ISSUE THREAD

**Issue by dimitriosxmi** [Nikoskak2000/The-hero-is-useless#16]
## Value Proposition

**As a** Developer  
**I want to** have a better Documentation structure in HackNPlan
**in order to** have better readabily and ease at navigating through the game design documentations
​

## Description

The structure should have design element types and design elements similar to this but in HackNPlan form
![Screenshot_3](https://github.com/Nikoskak2000/The-hero-is-useless/assets/31593501/c9e281e7-2e93-4339-8c40-b7b1dc460ed0)

## Acceptance Criteria

MVP:

- [ ] At least the design element types `Game Design`, `Units(All)`, `Level Design`, `Technical`, `Graphics`, and `Sound and Music` must be available (as seen in the screenshot)
- [ ] There should be a design element for most of the design elements visible in the screenshot, such as `Gameplay`, `Scenario Simplified`, `Development Abstract Classes`, `Development Derived Classes`, and so on.
(be the judge of what seems relevant and what not, and we will review it later on)
- [ ] Every design element should have a short description of what it is about

Nice to have:
- [ ] Every design element should have a template as the first child design element item that give's a sample of how the child design element items for the given design element are meant to be used, that way it can be cloned and the clone can be used to write a child design element item for the given design element.
      ​

## Tasks

- [ ] create the design element types in HackNPlan
- [ ] create the design elements
- [ ] write a description for every created design element
- [ ] [Nice to have] create a template child design element for every created design element
