### ISSUE TITLE
HackNPlan: Rules & Guidelines - Pipeline: Note to Completion

### ISSUE THREAD

**Issue by dimitriosxmi** [Nikoskak2000/The-hero-is-useless#17]
## Value Proposition

**As a** Developer
**I want to** have a design element on HackNPlan that teaches me the development pipeline in this project
**in order to** be better informed about it and not cause problems during development
​

## Description
​

## Acceptance Criteria

- [ ] [this linked design element](https://app.hacknplan.com/p/195992/gamemodel?nodeId=31&nodeTabId=description) must be used for it
- [ ] the descriptions about the pipeline should look into all these listed steps
  1. from anyone's random notes
  2. list text hereto idea
  3. to design documentation
  4. to development task
  5. to development
  6. to test
  7. to revision
  8. to design document adjustments (if outdated)
  9. to task completion
(circle 5-7 long as necessary)
- [ ] the descriptions may be splitted into individual child design elements but it is not recommended
- [ ] links, screenshots, pictures of graphs/ mindmaps, and/ or videos may be used in the explainations
- [ ] a tl;dr version should be provided, similar to the example list above, but a bit more detailed

## Tasks

- [ ] go to the [design element (click here)](https://app.hacknplan.com/p/195992/gamemodel?nodeId=31&nodeTabId=description)
- [ ] ensure the **Value Proposition** as well as **Acceptance Criteria** are met
